name: Build and Push Docker image to GHCR

on:
  # push:
  #   branches: [main]
  # pull_request:
  #   types: [closed]
  #   branches: [main]
  workflow_dispatch: 

jobs:
  push_to_ghcr:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write  

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Download and make allurectl executable
        run: |
          wget https://github.com/allure-framework/allurectl/releases/latest/download/allurectl_linux_amd64 -O ./allurectl
          chmod +x ./allurectl
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DEPLOY_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v7, linux/arm64/v8
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/py-allurectl:latest
          labels: |
            org.opencontainers.image.description=Python test runner with Allure and allurectl
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.licenses=MIT

